### ISSUE TITLE
更加激进的压缩

### ISSUE THREAD

**Issue by army8735** [army8735/more#7]
在出现优先级冲突时会进行检查不合并：
```css
.a{margin:0}.b{margin-top:1}.c{margin:0}
```
.a和.c无法合并，除非.b拥有!important。
其实如果.b的margin-top值是0也可以合并，现在有点难做，暂时记录。
另外是选择器也可以检查：在出现优先级冲突时会进行检查不合并：
```css
.a{margin:0}.a .b{margin-top:1}.c{margin:0}
```
如果中间冲突的选择器为前者的子选择器，则绝对不会出现冲突。
